LARGE_LITERAL_THRESHOLD = 1 * 1024 * 1024  # 1 MB

# Suffix marking stub values that reference large blobs in Azure
AZURE_CONTAINER_NAME = "abstrax-chemistry-large-nodes"

ENV_AZURE_STORAGE_CONNECTION_STRING = "AZURE_STORAGE_CONNECTION_STRING"

ENV_AZURE_LARGE_NODE_CONTAINER_SAS_TOKEN = "AZURE_LARGE_NODE_CONTAINER_SAS_TOKEN"

LARGE_NODE_IRI_SUFFIX = "__LARGE_NODE"

PYD_PUSH_TO_SPARQL_TEMPORARY_ONTOLOGY_IRI = "http://pyd.push.to.sparql/temporary.owl#"
